version: '3'

services:
  verdaccio:
    image: verdaccio/verdaccio
    restart: always
    container_name: verdaccio
    ports:
      - '4873:4873'
    volumes:
      - ./verdaccio-storage:/verdaccio/storage

volumes:
  verdaccio:
    driver: local